config/routes.rb
TOERH::Application.routes.draw do
  root 'api_key#index'

  post 'generate' => 'api_key#generate', as: :generate

  get 'docs' => 'documents#index'
  resources :admin, only: [:index, :destroy]

  get 'login' => 'auth#index', as: :showLogin
  post 'login' => 'auth#login', as: :login
  get 'logout' => 'auth#logout', as: :logout

  namespace :api do
    namespace :v1 do
      resources :resources, only: [:index, :show]
      
      post 'authenticate' => 'auth#authenticate'

      resources :licences, only: [:index, :show] do 
        resources :resources, only: :index
      end

      resources :resourcetypes, only: [:index, :show] do
        resources :resources, only: :index
      end

      resources :users, only: [:index, :show, :create, :update, :destroy] do
        resources :resources, only: [:index, :show, :create, :update, :destroy]
      end 
    end
  end 

  match "*path", to: "application#options", via: :options
  #match "*path", to: "errors#catch_404", via: :all
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
	validates :email, presence: {message: "Email can't be blank!"}, 
				uniqueness: {message: "Email already registered!"}

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "Invalid Email"
end

app/controllers/api_key_controller.rb
class ApiKeyController < ApplicationController
	def index

	end

	def generate
		apiKey = SecureRandom.hex(10)
		email = params[:email]

		app = ApiKey.create(api_key: apiKey, email: email)

		if app.invalid?
			flash[:error] = app.errors[:email].first
			return redirect_to :back
		end

		flash[:apiKey] = apiKey

		redirect_to :root
	end

	private

	def apiKey_params
		params.require(:email).permit(:email)
	end

end

app/helpers/api_key_helper.rb
module ApiKeyHelper
end

app/views/api_key/generate.html.erb
<h1>Here is your key</h1>

<p><%= @apiKey.apiKey %></p>

app/views/api_key/index.html.erb
<a class="to-docs btn" href="/docs">API documentation</a>
<a class="to-docs btn" href="/admin">Admin panel</a>
<h1>Enter your email below to generate your API-key</h1>

<%= flash[:error] %>

<%= form_tag(generate_path, method: "POST") do %>
	<%= text_field_tag(:email, nil, placeholder: 'Email') %>
	<%= submit_tag("Generate key", :class => 'btn') %>
<% end -%>

<% if flash[:apiKey] %>
	<div class="key-container box">
		<h2 class="key-title">Here is your credentials for using the API:</h2>
		
		<span>Apikey:</span>
		<p><%= flash[:apiKey] %></p>
	</div>
<% end %>